FROM python:3.7-alpine

WORKDIR /usr/src/app
RUN adduser -D -u 25000 -g app -h /usr/src/app app && \
    chown app:app /usr/src/app

# Necessary for install from GitHub
RUN apk add --update alpine-sdk

RUN pip install --no-cache-dir pipenv
COPY Pipfile* ./
RUN pipenv install --system --dev

VOLUME /usr/src/app
USER app
ENV PYTHONDONTWRITEBYTECODE=1
CMD [ "pytest" ]
